# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 2016 生醫電資營
email: ntu.bebi.stu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  2016 生醫電資營 展望未來十年：新世代生醫技術 個人化醫療的機會與挑戰
baseurl: "/camp2016" # the subpath of your site, e.g. /blog
url: "http://www.bebi.ntu.edu.tw" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude: ["build.sh", "sponsor.html", "assets/files"]